// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfsZrRa0rpBlz5-TUnJgcoP2t_HV9Z3MY',
    appId: '1:813102850892:web:7df701ecf81af40ccde5e9',
    messagingSenderId: '813102850892',
    projectId: 'mynotes1403',
    authDomain: 'mynotes1403.firebaseapp.com',
    storageBucket: 'mynotes1403.appspot.com',
    measurementId: 'G-X8TG0RSF69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATXyOn3_8-It-vMZCEj_iETWOm_2x2w9o',
    appId: '1:813102850892:android:21978672b58106b5cde5e9',
    messagingSenderId: '813102850892',
    projectId: 'mynotes1403',
    storageBucket: 'mynotes1403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgMl6Dtf4sS_DhHB7ix8UhRmaDFl-Ujks',
    appId: '1:813102850892:ios:1c68272a59ea9140cde5e9',
    messagingSenderId: '813102850892',
    projectId: 'mynotes1403',
    storageBucket: 'mynotes1403.appspot.com',
    iosClientId:
        '813102850892-mvs79lp5s2a78kib6dh81egeqstbdppi.apps.googleusercontent.com',
    iosBundleId: 'com.firstapp.mynotes',
  );
}
